= HDL SEC/DED Producer

MATLAB/Octave generator of Hamming ECC coder/decoder. Output format is Verilog HDL.
Optional adding atop Hamming Coding extra parity bit we have a Single Error Correction/Double Error Detection (SEC/DED) algorithm.

== Synopsis


== Getting Started


=== Prerequisites

You need installed on your host:

* MatLab
+
or
+
* GNU Octave

The GNU Octave required additional toolboxes, under RHEL/CentOS 6/7 systems please type for installs required prerequisites:
```
$ sudo yum install -y  octave-devel
$ octave
octave:> pkg install -forge control
octave:> pkg install -forge signal
octave:> pkg install -forge -verbose communications
```


=== Installing

Not needed to install

=== Usage

Just type (by default run matlab target):
  make

or if you can forcibly specify target:
  make matlab
or
  make octave


== ToDo

* Verilog module naming according to the data width


== Contributors

Please read link:CONTRIBUTING.adoc[] for details on our code of conduct, and the process for submitting pull requests to us.


== License

This project is licensed under the MIT License - see the link:LICENSE[] file for details


== References

* https://en.wikipedia.org/wiki/Hamming_code[Hamming codes] and https://en.wikipedia.org/wiki/Hamming_code#Hamming_codes_with_additional_parity_.28SECDED.29[SECDED section] (EN)
* https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%B4_%D0%A5%D1%8D%D0%BC%D0%BC%D0%B8%D0%BD%D0%B3%D0%B0[Hamming codes] (RU)
* http://www.xilinx.com/support/documentation/application_notes/xapp383.pdf[XAPP383: Single Error Correction and Double Error Detection]
* https://en.wikipedia.org/wiki/ECC_memory[Error-correcting code memory (ECC memory)]
* http://www.hackersdelight.org/ecc.pdf[ERROR CORRECTING CODES (PDF)]
* http://www.mathworks.com/help/comm/ref/hammgen.html[function hammgen() - Produce parity-check and generator matrices for Hamming code](EN)
* http://matlab.exponenta.ru/communication/book2/4/hammgen.php[MatLab function hammgen() from CommunicationsToolbox] (RU)
* http://math.ubbcluj.ro/~tradu/TI/html/hamex.html[MatLab Examples with Hamming codes]
* https://help.ubuntu.com/community/MATLAB[Useful link for setup MATLAB on the Linux host]

Feel free to send me comments, suggestions and bug reports

